// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BUlEJjBmT4jW-oQvVGJyxm0pgu2LJMM',
    appId: '1:259278528340:web:994c6ecadeba87738932c1',
    messagingSenderId: '259278528340',
    projectId: 'fullstore-ace88',
    authDomain: 'fullstore-ace88.firebaseapp.com',
    storageBucket: 'fullstore-ace88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATEy0Z18ujka3SLc0nNGDg4wlUyr7sSGw',
    appId: '1:259278528340:android:de6435953dd404128932c1',
    messagingSenderId: '259278528340',
    projectId: 'fullstore-ace88',
    storageBucket: 'fullstore-ace88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBhc3AUjq9Cd484ijG6U0jRwZUc4EU6I',
    appId: '1:259278528340:ios:cc529a5db384dd318932c1',
    messagingSenderId: '259278528340',
    projectId: 'fullstore-ace88',
    storageBucket: 'fullstore-ace88.appspot.com',
    iosBundleId: 'com.example.fullStore',
  );
}
